import { renderMarkdown } from '@/lib/markdown/pipeline';

/**
 * Export markdown as a PowerPoint (.pptx) file.
 * Splits content by h1/h2 headings into slides.
 */
export async function downloadAsPptx(
  filename: string,
  content: string,
  theme: 'dark' | 'light'
): Promise<void> {
  const PptxGenJS = (await import('pptxgenjs')).default;
  const html = await renderMarkdown(content);
  const title = filename.replace(/\.md$/i, '');

  const isDark = theme === 'dark';
  const bgColor = isDark ? '0d1117' : 'ffffff';
  const textColor = isDark ? 'e6edf3' : '1f2328';
  const titleColor = isDark ? 'a5b4fc' : '4f46e5';
  const subtextColor = isDark ? '8b949e' : '656d76';

  // Parse HTML and split by headings
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');

  interface SlideData {
    title: string;
    level: number;
    content: string[];
    tables: string[][][];
  }

  const slides: SlideData[] = [];
  let currentSlide: SlideData | null = null;

  Array.from(doc.body.children).forEach((el) => {
    const tag = el.tagName.toLowerCase();

    if (tag === 'h1' || tag === 'h2') {
      if (currentSlide) slides.push(currentSlide);
      currentSlide = { title: el.textContent || '', level: tag === 'h1' ? 1 : 2, content: [], tables: [] };
      return;
    }

    if (!currentSlide) {
      // Content before first heading → create title slide
      currentSlide = { title: title, level: 0, content: [], tables: [] };
    }

    if (tag === 'table') {
      const rows: string[][] = [];
      el.querySelectorAll('tr').forEach((tr) => {
        const cells: string[] = [];
        tr.querySelectorAll('th, td').forEach((cell) => {
          cells.push(cell.textContent || '');
        });
        rows.push(cells);
      });
      if (rows.length > 0) currentSlide!.tables.push(rows);
    } else if (tag === 'ul' || tag === 'ol') {
      el.querySelectorAll(':scope > li').forEach((li) => {
        currentSlide!.content.push('• ' + (li.textContent || '').trim());
      });
    } else if (tag === 'pre') {
      const code = el.querySelector('code')?.textContent || el.textContent || '';
      currentSlide!.content.push(code.trim());
    } else {
      const text = (el.textContent || '').trim();
      if (text) currentSlide!.content.push(text);
    }
  });

  if (currentSlide) slides.push(currentSlide);

  // Create presentation
  const pptx = new PptxGenJS();
  pptx.title = title;
  pptx.author = 'MarkView';
  pptx.layout = 'LAYOUT_WIDE';

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { fill: bgColor };
  titleSlide.addText(title, {
    x: 0.5, y: 1.5, w: '90%', h: 1.5,
    fontSize: 36, color: titleColor, fontFace: 'Inter',
    align: 'center', bold: true,
  });
  titleSlide.addText('Generated by MarkView', {
    x: 0.5, y: 3.5, w: '90%', h: 0.5,
    fontSize: 14, color: subtextColor, fontFace: 'Inter',
    align: 'center',
  });

  // Content slides
  for (const s of slides) {
    if (s.level === 0 && s.content.length === 0 && s.tables.length === 0) continue;

    const slide = pptx.addSlide();
    slide.background = { fill: bgColor };

    // Slide title
    slide.addText(s.title, {
      x: 0.5, y: 0.3, w: '90%', h: 0.8,
      fontSize: s.level <= 1 ? 28 : 24,
      color: titleColor, fontFace: 'Inter', bold: true,
    });

    // Content text
    if (s.content.length > 0) {
      const bodyText = s.content.join('\n');
      const truncated = bodyText.length > 1500 ? bodyText.slice(0, 1500) + '...' : bodyText;
      slide.addText(truncated, {
        x: 0.5, y: 1.3, w: '90%', h: 4,
        fontSize: 14, color: textColor, fontFace: 'Inter',
        valign: 'top', paraSpaceAfter: 6,
      });
    }

    // Tables (first one only to avoid overflow)
    if (s.tables.length > 0 && s.content.length === 0) {
      const tableData = s.tables[0];
      const pptxRows = tableData.map((row, rIdx) =>
        row.map((cell) => ({
          text: cell,
          options: {
            fontSize: 11,
            color: textColor,
            fontFace: 'Inter',
            bold: rIdx === 0,
            fill: { color: rIdx === 0 ? (isDark ? '161b22' : 'f6f8fa') : bgColor },
          },
        }))
      );
      slide.addTable(pptxRows, {
        x: 0.5, y: 1.3, w: '90%',
        border: { pt: 0.5, color: isDark ? '30363d' : 'd0d7de' },
        colW: Array(tableData[0]?.length || 1).fill(12 / (tableData[0]?.length || 1)),
        fontSize: 11,
        autoPage: true,
      });
    }
  }

  await pptx.writeFile({ fileName: `${title}.pptx` });
}
