// SPDX-License-Identifier: Apache-2.0

/**
 * Curated GitHub-style emoji shortcodes → unicode. Covers the common set
 * people actually type; unknown `:codes:` are left literal by the inline
 * plugin. Dependency-free on purpose (a full emoji table is ~1800 entries).
 */
export const EMOJI: Record<string, string> = {
  smile: '😄', smiley: '😃', grin: '😁', laughing: '😆', joy: '😂', rofl: '🤣',
  wink: '😉', blush: '😊', heart_eyes: '😍', kissing_heart: '😘',
  thinking: '🤔', neutral_face: '😐', expressionless: '😑', unamused: '😒',
  sweat_smile: '😅', sob: '😭', cry: '😢', angry: '😠', rage: '😡',
  sunglasses: '😎', nerd_face: '🤓', smirk: '😏', scream: '😱', flushed: '😳',
  sleeping: '😴', yum: '😋', stuck_out_tongue: '😛', zany_face: '🤪',
  exploding_head: '🤯', partying_face: '🥳', pleading_face: '🥺',
  heart: '❤️', orange_heart: '🧡', yellow_heart: '💛', green_heart: '💚',
  blue_heart: '💙', purple_heart: '💜', black_heart: '🖤', broken_heart: '💔',
  sparkling_heart: '💖', heartpulse: '💗', two_hearts: '💕',
  thumbsup: '👍', '+1': '👍', thumbsdown: '👎', '-1': '👎', ok_hand: '👌',
  clap: '👏', raised_hands: '🙌', pray: '🙏', muscle: '💪', point_right: '👉',
  point_left: '👈', point_up: '☝️', point_down: '👇', wave: '👋', fist: '✊',
  v: '✌️', crossed_fingers: '🤞', handshake: '🤝', writing_hand: '✍️',
  fire: '🔥', sparkles: '✨', star: '⭐', star2: '🌟', boom: '💥', zap: '⚡',
  tada: '🎉', confetti_ball: '🎊', balloon: '🎈', gift: '🎁', trophy: '🏆',
  medal: '🏅', rocket: '🚀', sunny: '☀️', cloud: '☁️', rainbow: '🌈',
  snowflake: '❄️', droplet: '💧', ocean: '🌊', moon: '🌙', earth_americas: '🌎',
  check: '✅', white_check_mark: '✅', heavy_check_mark: '✔️', x: '❌',
  negative_squared_cross_mark: '❎', warning: '⚠️', no_entry: '⛔',
  question: '❓', grey_question: '❔', exclamation: '❗', bangbang: '‼️',
  information_source: 'ℹ️', bulb: '💡', bell: '🔔', lock: '🔒', unlock: '🔓',
  key: '🔑', mag: '🔍', link: '🔗', pushpin: '📌', paperclip: '📎',
  pencil: '✏️', pencil2: '✏️', memo: '📝', book: '📖', books: '📚',
  bookmark: '🔖', clipboard: '📋', calendar: '📅', email: '📧', envelope: '✉️',
  inbox_tray: '📥', outbox_tray: '📤', package: '📦', wastebasket: '🗑️',
  computer: '💻', desktop_computer: '🖥️', keyboard: '⌨️', iphone: '📱',
  battery: '🔋', electric_plug: '🔌', satellite: '🛰️', gear: '⚙️',
  hammer: '🔨', wrench: '🔧', nut_and_bolt: '🔩', toolbox: '🧰', bug: '🐛',
  microscope: '🔬', telescope: '🔭', test_tube: '🧪', dna: '🧬', brain: '🧠',
  robot: '🤖', alien: '👽', ghost: '👻', skull: '💀', poop: '💩', clown: '🤡',
  eyes: '👀', eye: '👁️', speech_balloon: '💬', thought_balloon: '💭',
  zzz: '💤', dash: '💨', anchor: '⚓', hourglass: '⌛', watch: '⌚',
  alarm_clock: '⏰', stopwatch: '⏱️', coffee: '☕', tea: '🍵', beer: '🍺',
  pizza: '🍕', hamburger: '🍔', taco: '🌮', apple: '🍎', banana: '🍌',
  cake: '🍰', birthday: '🎂', cookie: '🍪', chocolate_bar: '🍫', candy: '🍬',
  dog: '🐶', cat: '🐱', mouse: '🐭', fox_face: '🦊', bear: '🐻', panda_face: '🐼',
  penguin: '🐧', bird: '🐦', unicorn: '🦄', dragon: '🐉', butterfly: '🦋',
  seedling: '🌱', herb: '🌿', four_leaf_clover: '🍀', maple_leaf: '🍁',
  flower: '🌸', rose: '🌹', sunflower: '🌻', cactus: '🌵', evergreen_tree: '🌲',
  100: '💯', musical_note: '🎵', notes: '🎶', art: '🎨', clapper: '🎬',
  camera: '📷', video_camera: '📹', microphone: '🎤', headphones: '🎧',
  game_die: '🎲', dart: '🎯', soccer: '⚽', basketball: '🏀', football: '🏈',
  money_with_wings: '💸', moneybag: '💰', dollar: '💵', credit_card: '💳',
  chart_with_upwards_trend: '📈', chart_with_downwards_trend: '📉', bar_chart: '📊',
  hot_pepper: '🌶️', snail: '🐌', turtle: '🐢', honeybee: '🐝',
};
