'use client';

import { useState, useRef } from 'react';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { BrowserWebRTCClientTransport } from '@/lib/mcp/BrowserWebRTCClientTransport';
import { FiTerminal, FiPlay, FiServer, FiCheckCircle, FiXCircle } from 'react-icons/fi';

export function AgentDemo() {
  const [roomId, setRoomId] = useState('demo-room');
  const [status, setStatus] = useState<'idle' | 'connecting' | 'connected' | 'error'>('idle');
  const [logs, setLogs] = useState<{ id: number; text: string; type: 'info' | 'success' | 'error' | 'data' }[]>([]);
  
  const clientRef = useRef<Client | null>(null);
  const logCounter = useRef(0);

  const addLog = (text: string, type: 'info' | 'success' | 'error' | 'data' = 'info') => {
    setLogs((prev) => [...prev, { id: logCounter.current++, text, type }]);
  };

  const handleConnect = async () => {
    if (!roomId) return;
    setStatus('connecting');
    addLog(`Connecting to local room: ${roomId}...`);

    try {
      const transport = new BrowserWebRTCClientTransport(roomId, 'ws://localhost:4444');
      
      const client = new Client({
        name: 'markview-web-agent',
        version: '1.0.0',
      });

      addLog(`Waiting for WebRTC Data Channel to open...`);
      await client.connect(transport);
      
      clientRef.current = client;
      setStatus('connected');
      addLog(`✅ Zero-Trust WebRTC connection established natively!`, 'success');
      
    } catch (e: any) {
      console.error(e);
      setStatus('error');
      addLog(`Connection failed: ${e.message}`, 'error');
    }
  };

  const handleDisconnect = async () => {
    if (clientRef.current) {
      await clientRef.current.close();
      clientRef.current = null;
    }
    setStatus('idle');
    addLog(`Disconnected from local node.`, 'info');
  };

  const executeTool = async (toolName: string, args: any = {}) => {
    if (!clientRef.current) return;
    
    addLog(`> Executing native tool: ${toolName}`, 'info');
    try {
      const result = await clientRef.current.callTool({
        name: toolName,
        arguments: args
      });
      
      addLog(JSON.stringify(result, null, 2), 'data');
    } catch (e: any) {
      addLog(`Tool execution failed: ${e.message}`, 'error');
    }
  };

  return (
    <div className="flex flex-col h-full bg-zinc-950 text-white rounded-xl border border-white/10 overflow-hidden shadow-2xl">
      {/* Header */}
      <div className="border-b border-white/10 p-4 bg-zinc-900/50 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-white/5 flex items-center justify-center border border-white/10">
            <FiServer className="w-5 h-5 text-zinc-400" />
          </div>
          <div>
            <h2 className="font-semibold">MarkView Universal Plaid Bridge</h2>
            <p className="text-xs text-zinc-400">Zero-Install Peer-to-Peer Context Engine</p>
          </div>
        </div>
        
        {status === 'connected' ? (
          <div className="flex items-center gap-2 px-3 py-1.5 bg-emerald-500/10 text-emerald-400 rounded-full text-sm font-medium border border-emerald-500/20">
            <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
            Connected Locally
          </div>
        ) : status === 'connecting' ? (
          <div className="flex items-center gap-2 px-3 py-1.5 bg-amber-500/10 text-amber-400 rounded-full text-sm font-medium border border-amber-500/20">
            <div className="w-4 h-4 rounded-full border-2 border-amber-500/20 border-t-amber-500 animate-spin" />
            Negotiating P2P...
          </div>
        ) : (
          <div className="flex items-center gap-2 px-3 py-1.5 bg-zinc-800 text-zinc-400 rounded-full text-sm font-medium border border-white/5">
            <div className="w-2 h-2 rounded-full bg-zinc-500" />
            Disconnected
          </div>
        )}
      </div>

      {/* Main Content Split */}
      <div className="flex-1 flex overflow-hidden">
        {/* Connection Panel */}
        <div className="w-80 border-r border-white/10 bg-zinc-900/30 p-6 flex flex-col gap-6">
          {status === 'idle' || status === 'error' ? (
            <div className="space-y-4">
              <h3 className="text-sm font-medium text-zinc-300 uppercase tracking-wider">Connect Local Node</h3>
              <p className="text-sm text-zinc-400">Enter the room ID generated by your local `markview-mcp` CLI to establish a direct WebRTC pipeline.</p>
              
              <div className="space-y-2">
                <label className="text-xs text-zinc-500 uppercase tracking-widest font-semibold">Room ID</label>
                <input 
                  type="text" 
                  value={roomId}
                  onChange={(e) => setRoomId(e.target.value)}
                  className="w-full bg-black/50 border border-white/10 rounded-lg px-4 py-2 text-sm focus:outline-none focus:border-indigo-500 transition-colors"
                  placeholder="e.g. secret-room-123"
                />
              </div>

              <button 
                onClick={handleConnect}
                className="w-full py-2.5 bg-white text-black font-semibold rounded-lg hover:bg-zinc-200 transition-colors flex items-center justify-center gap-2 mt-4"
              >
                <FiTerminal /> Connect Securely
              </button>
            </div>
          ) : (
            <div className="space-y-6">
              <div className="p-4 bg-emerald-500/5 border border-emerald-500/20 rounded-xl space-y-3">
                <h3 className="text-sm font-semibold text-emerald-400 flex items-center gap-2">
                  <FiCheckCircle /> Bridge Active
                </h3>
                <p className="text-xs text-zinc-400">
                  This browser tab now has true read/execute access over your local terminal via a native WebRTC DataChannel. No cloud databases are involved.
                </p>
                <button 
                  onClick={handleDisconnect}
                  className="w-full py-2 bg-red-500/10 text-red-400 font-medium rounded-lg hover:bg-red-500/20 transition-colors text-sm border border-red-500/20 mt-2"
                >
                  Terminate Connection
                </button>
              </div>

              <div className="space-y-3">
                <h3 className="text-xs font-semibold uppercase tracking-wider text-zinc-500">Demo Remote Tools</h3>
                
                <button 
                  onClick={() => executeTool('workspace-overview')}
                  className="w-full text-left px-4 py-3 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-colors group"
                >
                  <div className="text-sm font-medium text-white group-hover:text-indigo-400 transition-colors flex items-center justify-between">
                    workspace-overview <FiPlay className="opacity-0 group-hover:opacity-100 transition-opacity" />
                  </div>
                  <div className="text-xs text-zinc-500 mt-1">Get entire docs directory stats</div>
                </button>

                <button 
                  onClick={() => executeTool('list_documents')}
                  className="w-full text-left px-4 py-3 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-colors group"
                >
                  <div className="text-sm font-medium text-white group-hover:text-indigo-400 transition-colors flex items-center justify-between">
                    list_documents <FiPlay className="opacity-0 group-hover:opacity-100 transition-opacity" />
                  </div>
                  <div className="text-xs text-zinc-500 mt-1">Scan terminal for Markdown files</div>
                </button>

                <button 
                  onClick={() => executeTool('analyze_reading_level')}
                  className="w-full text-left px-4 py-3 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-colors group"
                >
                  <div className="text-sm font-medium text-white group-hover:text-indigo-400 transition-colors flex items-center justify-between">
                    analyze_reading_level <FiPlay className="opacity-0 group-hover:opacity-100 transition-opacity" />
                  </div>
                  <div className="text-xs text-zinc-500 mt-1">Run Flesch-Kincaid NLP on local files</div>
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Terminal/Log Window */}
        <div className="flex-1 bg-black p-6 font-mono text-sm overflow-y-auto relative">
          <div className="absolute inset-0 pointer-events-none bg-[radial-gradient(circle_at_center,rgba(255,255,255,0.03)_1px,transparent_1px)] bg-[size:24px_24px] opacity-20" />
          
          <div className="relative z-10 space-y-3 pb-8">
            <div className="text-zinc-500 mb-6 font-semibold">
              // MarkView WebRTC Terminal<br/>
              // All execution payload securely streams over RTCPeerConnection.
            </div>
            
            {logs.map(log => (
              <div key={log.id} className={`whitespace-pre-wrap break-all ${
                log.type === 'error' ? 'text-red-400' :
                log.type === 'success' ? 'text-emerald-400 font-semibold' :
                log.type === 'data' ? 'text-indigo-300 bg-indigo-500/10 p-4 rounded-lg border border-indigo-500/20' :
                'text-zinc-300'
              }`}>
                {log.text}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
